# Site settings
title: Dark Art Laboratories
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A technologist's blog of code, security, clouds and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://darkarts.netlify.com/" # the base hostname & protocol for your site
twitter_username: Dark_Arts_Sec
github_username:  tjonestech

# Build settings
markdown: kramdown
